[package]
name = "viz"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
colored = "3.0.0"
indexmap = { version = "2.7.1", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.138", features = ["preserve_order"] }
thiserror = "2.0.11"
toml = { version = "0.8.20", features = ["preserve_order"] }
